### PR TITLE
Support for priors on parameters

### PR DESCRIPTION
**Pull request by sethaxen**
This PR adds support for users specifying priors on parameters, similarly to in [GPflow](https://gpflow.github.io/GPflow/develop/notebooks/getting_started/parameters_and_their_optimisation.html#Priors). Specifically it makes 2 changes
- All classes defined in markovflow that currently inherit `tf.Module` now inherit `gpflow.Module` (also a child of `tf.Module`), which adds a `trainable_parameters` attribute to all of these classes. Unlike `trainable_variables`, this attribute returns `gpflow.Parameter` objects, which are variables that also have priors.
- Add `log_prior_density` methods to the model base classes, so that `model.log_prior_density()` can be used to compute the log prior density for all trainable parameters with priors. This function is copied from gpflow.

As an added benefit, the classes that inherit `gpflow.Module` inherit some of the useful pretty-printing. e.g. from https://github.com/secondmind-labs/markovflow/blob/7c5ef608340f0a259b8111ab77ea5924c07d7dbb/docs/notebooks/spatio_temporal.py

<details>

```ipython
In [3]: kernel_time
Out[3]: 
<markovflow.kernels.matern.Matern32 object at 0x7f43fb4e3c90>
╒═══════════════════════╤═══════════╤═════════════╤═════════╤═════════════╤═════════╤═════════╤═════════╕
│ name                  │ class     │ transform   │ prior   │ trainable   │ shape   │ dtype   │ value   │
╞═══════════════════════╪═══════════╪═════════════╪═════════╪═════════════╪═════════╪═════════╪═════════╡
│ Matern32._state_mean  │ Parameter │ Identity    │         │ False       │ (2,)    │ float64 │ [0. 0.] │
├───────────────────────┼───────────┼─────────────┼─────────┼─────────────┼─────────┼─────────┼─────────┤
│ Matern32._lengthscale │ Parameter │ Softplus    │         │ True        │ ()      │ float64 │ 2.5     │
├───────────────────────┼───────────┼─────────────┼─────────┼─────────────┼─────────┼─────────┼─────────┤
│ Matern32._variance    │ Parameter │ Softplus    │         │ True        │ ()      │ float64 │ 1.0     │
╘═══════════════════════╧═══════════╧═════════════╧═════════╧═════════════╧═════════╧═════════╧═════════╛

In [5]: model
Out[5]: 
<markovflow.models.spatio_temporal_variational.SpatioTemporalSparseCVI object at 0x7f43fb501cd0>
╒═══════════════════════════════════════════════════════════╤═══════════╤══════════════════╤═════════╤═════════════╤═════════════╤═════════╤═════════════════════╕
│ name                                                      │ class     │ transform        │ prior   │ trainable   │ shape       │ dtype   │ value               │
╞═══════════════════════════════════════════════════════════╪═══════════╪══════════════════╪═════════╪═════════════╪═════════════╪═════════╪═════════════════════╡
│ SpatioTemporalSparseCVI._kernel_space.variance            │ Parameter │ Softplus         │         │ True        │ ()          │ float64 │ 1.0                 │
│ SpatioTemporalSparseCVI._kernel.kernel_space.variance     │           │                  │         │             │             │         │                     │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI._kernel_space.lengthscales        │ Parameter │ Softplus         │         │ True        │ ()          │ float64 │ 0.5                 │
│ SpatioTemporalSparseCVI._kernel.kernel_space.lengthscales │           │                  │         │             │             │         │                     │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI._kernel_time._state_mean          │ Parameter │ Identity         │         │ False       │ (2,)        │ float64 │ [0. 0.]             │
│ SpatioTemporalSparseCVI._kernel.kernel_time._state_mean   │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[0]._state_mean   │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[1]._state_mean   │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[2]._state_mean   │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[3]._state_mean   │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[4]._state_mean   │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[5]._state_mean   │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[6]._state_mean   │           │                  │         │             │             │         │                     │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI._kernel_time._lengthscale         │ Parameter │ Softplus         │         │ True        │ ()          │ float64 │ 2.5                 │
│ SpatioTemporalSparseCVI._kernel.kernel_time._lengthscale  │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[0]._lengthscale  │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[1]._lengthscale  │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[2]._lengthscale  │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[3]._lengthscale  │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[4]._lengthscale  │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[5]._lengthscale  │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[6]._lengthscale  │           │                  │         │             │             │         │                     │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI._kernel_time._variance            │ Parameter │ Softplus         │         │ True        │ ()          │ float64 │ 1.0                 │
│ SpatioTemporalSparseCVI._kernel.kernel_time._variance     │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[0]._variance     │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[1]._variance     │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[2]._variance     │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[3]._variance     │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[4]._variance     │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[5]._variance     │           │                  │         │             │             │         │                     │
│ SpatioTemporalSparseCVI._kernel._kernels[6]._variance     │           │                  │         │             │             │         │                     │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI._likelihood.variance              │ Parameter │ Softplus + Shift │         │ True        │ ()          │ float64 │ 0.09999999999999999 │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI._kernel._state_mean               │ Parameter │ Identity         │         │ False       │ (14,)       │ float64 │ [0., 0., 0....      │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI.nat1                              │ Parameter │ Identity         │         │ True        │ (8, 28)     │ float64 │ [[0., 0., 0....     │
├───────────────────────────────────────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────────┼─────────┼─────────────────────┤
│ SpatioTemporalSparseCVI.nat2                              │ Parameter │ Identity         │         │ True        │ (8, 28, 28) │ float64 │ [[[0., 0., 0....    │
╘═══════════════════════════════════════════════════════════╧═══════════╧══════════════════╧═════════╧═════════════╧═════════════╧═════════╧═════════════════════╛
```
</details>

### CODE REVIEW

**Review by vincentadam87 — APPROVED** [review]
looks good to me!

**Comment by vincentadam87** [comment]
ping me when this is ready (this is marked as a draft)

**Comment by sethaxen** [comment]
@vincentadam87 I have added the necessary tests and this should now be ready to merge.

**Comment by vincentadam87** [comment]
tests look good to me!

**Pull request merged**
